<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="5" total="12" passed="7">
  <reporter-output>
  </reporter-output>
  <suite name="Suite1" duration-ms="147617" started-at="2016-06-16T08:46:37Z" finished-at="2016-06-16T08:49:05Z">
    <groups>
    </groups>
    <test name="Regression Test Suite" duration-ms="147617" started-at="2016-06-16T08:46:37Z" finished-at="2016-06-16T08:49:05Z">
      <class name="com.cybage.alm.test.TestSuite2">
        <test-method status="PASS" signature="loginTest(com.cybage.alm.data.LoginData)[pri:1, instance:com.cybage.alm.test.TestSuite2@460d0a57]" name="loginTest" duration-ms="10943" started-at="2016-06-16T14:16:38Z" data-provider="loginData" finished-at="2016-06-16T14:16:49Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.cybage.alm.data.LoginData@54227100]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="loginTest(com.cybage.alm.data.LoginData)[pri:1, instance:com.cybage.alm.test.TestSuite2@460d0a57]" name="loginTest" duration-ms="10530" started-at="2016-06-16T14:16:49Z" data-provider="loginData" finished-at="2016-06-16T14:16:59Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.cybage.alm.data.LoginData@6b5894c8]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="FAIL" signature="loginTest(com.cybage.alm.data.LoginData)[pri:1, instance:com.cybage.alm.test.TestSuite2@460d0a57]" name="loginTest" duration-ms="9235" started-at="2016-06-16T14:16:59Z" data-provider="loginData" finished-at="2016-06-16T14:17:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.cybage.alm.data.LoginData@33e01298]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [SIGN-ON] but found [SIGN-OFF]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [SIGN-ON] but found [SIGN-OFF]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.cybage.alm.pages.LoginPage.signin(LoginPage.java:18)
	at com.cybage.alm.test.TestSuite2.loginTest(TestSuite2.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="FAIL" signature="loginTest(com.cybage.alm.data.LoginData)[pri:1, instance:com.cybage.alm.test.TestSuite2@460d0a57]" name="loginTest" duration-ms="11367" started-at="2016-06-16T14:17:08Z" data-provider="loginData" finished-at="2016-06-16T14:17:20Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.cybage.alm.data.LoginData@a5b0b86]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [SIGN-ON] but found [SIGN-OFF]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [SIGN-ON] but found [SIGN-OFF]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.cybage.alm.pages.LoginPage.signin(LoginPage.java:18)
	at com.cybage.alm.test.TestSuite2.loginTest(TestSuite2.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="FAIL" signature="loginTest(com.cybage.alm.data.LoginData)[pri:1, instance:com.cybage.alm.test.TestSuite2@460d0a57]" name="loginTest" duration-ms="9735" started-at="2016-06-16T14:17:20Z" data-provider="loginData" finished-at="2016-06-16T14:17:29Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.cybage.alm.data.LoginData@78fb9a67]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [SIGN-ON] but found [SIGN-OFF]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [SIGN-ON] but found [SIGN-OFF]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.cybage.alm.pages.LoginPage.signin(LoginPage.java:18)
	at com.cybage.alm.test.TestSuite2.loginTest(TestSuite2.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="FAIL" signature="loginTest(com.cybage.alm.data.LoginData)[pri:1, instance:com.cybage.alm.test.TestSuite2@460d0a57]" name="loginTest" duration-ms="10901" started-at="2016-06-16T14:17:29Z" data-provider="loginData" finished-at="2016-06-16T14:17:40Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.cybage.alm.data.LoginData@21aa6d6c]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [SIGN-ON] but found [SIGN-OFF]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [SIGN-ON] but found [SIGN-OFF]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.cybage.alm.pages.LoginPage.signin(LoginPage.java:18)
	at com.cybage.alm.test.TestSuite2.loginTest(TestSuite2.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="FAIL" signature="loginTest(com.cybage.alm.data.LoginData)[pri:1, instance:com.cybage.alm.test.TestSuite2@460d0a57]" name="loginTest" duration-ms="10202" started-at="2016-06-16T14:17:40Z" data-provider="loginData" finished-at="2016-06-16T14:17:51Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.cybage.alm.data.LoginData@2f9a01c1]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [SIGN-ON] but found [SIGN-OFF]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [SIGN-ON] but found [SIGN-OFF]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.cybage.alm.pages.LoginPage.signin(LoginPage.java:18)
	at com.cybage.alm.test.TestSuite2.loginTest(TestSuite2.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="loginTest(com.cybage.alm.data.LoginData)[pri:1, instance:com.cybage.alm.test.TestSuite2@460d0a57]" name="loginTest" duration-ms="11549" started-at="2016-06-16T14:17:51Z" data-provider="loginData" finished-at="2016-06-16T14:18:02Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.cybage.alm.data.LoginData@1433046b]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="registerTest(com.cybage.alm.data.RegisterData)[pri:2, instance:com.cybage.alm.test.TestSuite2@460d0a57]" name="registerTest" duration-ms="18502" started-at="2016-06-16T14:18:02Z" data-provider="registerData" finished-at="2016-06-16T14:18:21Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.cybage.alm.data.RegisterData@3f446bef]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registerTest -->
        <test-method status="PASS" signature="registerTest(com.cybage.alm.data.RegisterData)[pri:2, instance:com.cybage.alm.test.TestSuite2@460d0a57]" name="registerTest" duration-ms="17662" started-at="2016-06-16T14:18:21Z" data-provider="registerData" finished-at="2016-06-16T14:18:38Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.cybage.alm.data.RegisterData@7829b776]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registerTest -->
        <test-method status="PASS" signature="registerTest(com.cybage.alm.data.RegisterData)[pri:2, instance:com.cybage.alm.test.TestSuite2@460d0a57]" name="registerTest" duration-ms="15724" started-at="2016-06-16T14:18:38Z" data-provider="registerData" finished-at="2016-06-16T14:18:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.cybage.alm.data.RegisterData@5778826f]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registerTest -->
        <test-method status="PASS" signature="registerTest(com.cybage.alm.data.RegisterData)[pri:2, instance:com.cybage.alm.test.TestSuite2@460d0a57]" name="registerTest" duration-ms="10882" started-at="2016-06-16T14:18:54Z" data-provider="registerData" finished-at="2016-06-16T14:19:05Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.cybage.alm.data.RegisterData@5b64c4b7]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registerTest -->
        <test-method status="PASS" signature="teadDown()[pri:0, instance:com.cybage.alm.test.TestSuite2@460d0a57]" name="teadDown" is-config="true" duration-ms="1" started-at="2016-06-16T14:19:05Z" finished-at="2016-06-16T14:19:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teadDown -->
      </class> <!-- com.cybage.alm.test.TestSuite2 -->
    </test> <!-- Regression Test Suite -->
  </suite> <!-- Suite1 -->
</testng-results>
